version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kobetransfer
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
      runas: root